version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g serverless eslint jest
  build:
    commands:
      # linting and unit tests
      - npm run-script lint
      - npm test
      # deploy integration testing environment
      - serverless deploy --stage test -v
      # integration tests
      - npm run-script integration
      # create directory for deployment packages
      - mkdir artifacts
      # create staging deployment package
      - mkdir artifacts/stg
      - serverless package --package artifacts/stg --stage stg -v
      # create prod deployment package
      - mkdir artifacts/prod
      - serverless package --package artifacts/prod --stage prod -v
  post_build:
    commands:
      - serverless remove --stage test -v

  artifacts:
    files:
      # export artifacts needed for staging and prod deployments to an S3 bucket
      - artifacts/**/*
      - serverless.yml
      - deploy.sh