version: 0.2

phases:
  install:
    commands:
      # remove package-lock before updating npm, otherwise not all dependencies will install
      - rm package-lock.json
      # update npm to 5.6.0 due to package-lock bug: https://github.com/npm/npm/issues/18135
      - npm install --silent --progress=false -g npm
      # install dependencies
      - npm install --silent --progress=false -g serverless
      - npm install --silent --progress-false
      - npm --version
  build:
    commands:
      # linting and unit tests
      - npm run-script lint
      - npm test
      # deploy integration testing environment
      - serverless deploy --stage test -v
      # integration tests
      - npm run-script integration]